apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: auth-system
  labels:
    app.kubernetes.io/name: auth-server
    app.kubernetes.io/component: config
data:
  # Server Configuration
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"
  SERVER_ENVIRONMENT: "production"
  SERVER_READ_TIMEOUT: "10s"
  SERVER_WRITE_TIMEOUT: "10s"
  
  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "auth_db"
  DB_USER: "auth_user"
  DB_SSL_MODE: "require"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Auth Configuration
  JWT_ISSUER: "https://auth.your-domain.com"
  JWT_AUDIENCE: "auth-clients"
  ACCESS_TOKEN_EXPIRY: "15m"
  REFRESH_TOKEN_EXPIRY: "720h"
  AUTH_CODE_EXPIRY: "10m"
  SESSION_EXPIRY: "24h"
  
  # Security Configuration
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "1h"
  PASSWORD_MIN_LENGTH: "8"
  MAX_LOGIN_ATTEMPTS: "5"
  LOCKOUT_DURATION: "30m"
  
  # LDAP Configuration (if using LDAP)
  LDAP_PORT: "389"
  LDAP_USER_FILTER: "(uid=%s)"
  LDAP_ADMIN_GROUP: "admin"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config-dev
  namespace: auth-system-dev
  labels:
    app.kubernetes.io/name: auth-server
    app.kubernetes.io/component: config
    environment: development
data:
  # Development overrides
  SERVER_ENVIRONMENT: "development"
  DB_SSL_MODE: "disable"
  JWT_ISSUER: "http://auth.local"
  ACCESS_TOKEN_EXPIRY: "1h"  # Longer for development