# Kustomization file for production deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: auth-server

# Common labels applied to all resources (updated syntax)
labels:
  - pairs:
      app.kubernetes.io/part-of: auth-system
      app.kubernetes.io/managed-by: kustomize

# Namespace for all resources
namespace: auth-system

# Resources to deploy
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - auth-server.yaml
  - ingress.yaml
  - monitoring.yaml

# Images to replace (for CI/CD)
images:
  - name: IMAGE_TAG_PLACEHOLDER
    newName: ghcr.io/sleeplesssheep/go_auth
    newTag: latest

# Config map generator for environment-specific values
configMapGenerator:
  - name: build-info
    literals:
      - BUILD_VERSION=1.0.0
      - BUILD_COMMIT=unknown
      - BUILD_DATE=unknown

# Replicas for production
replicas:
  - name: auth-server
    count: 2