# Development environment patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: auth-system-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: auth-server
        # Development-specific env vars
        env:
        - name: GIN_MODE
          value: "debug"
        - name: LOG_LEVEL
          value: "debug"
        # Relaxed resource limits for development
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        # Faster health checks for development
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 3

---
# Development PostgreSQL with less strict settings
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: auth-system-dev
spec:
  template:
    spec:
      containers:
      - name: postgres
        # Relaxed resource limits
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
# Development service (NodePort for easy access)
apiVersion: v1
kind: Service
metadata:
  name: auth-service-dev
  namespace: auth-system-dev
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: auth-server
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    name: http